put script directly in the metadata file

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,8 +17,26 @@ inputs:
 runs:
   using: composite
   steps:
-    - run: script.sh
-      shell: sh
+    - name: Check remote_host Empty
+      if: ${{ inputs.remote_host == '' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::remote_host empty, Maybe you need to populate it in the Secrets for your workflow, see more in https://docs.github.com/en/actions/security-guides/encrypted-secrets"
+        exit 1
+    - name: Check directory Empty
+      if: ${{ inputs.directory == '' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::directory empty, Maybe you need to populate it in the Secrets for your workflow, see more in https://docs.github.com/en/actions/security-guides/encrypted-secrets"
+        exit 1
+    - run: |
+        tar cjvf - -C "$GITHUB_WORKSPACE" "$DIRECTORY" | ssh -o StrictHostKeyChecking=no "$REMOTE_HOST" "cd $REMOTE_DESTINATION && tar -xjvf -"
+        shell: sh
+    - name: execute a post upload command if specified
+      if: ${{ inputs.post_upload_command }}
+      run: |
+        echo "Upload post command specified, runnig. $POST_UPLOAD_COMMAND"
+        ssh -o StrictHostKeyChecking=no "$REMOTE_HOST" "eval $POST_UPLOAD_COMMAND"
 
 branding:
   icon: terminal
